apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-cloudcraft-service
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        app: {{ .Release.Name }}-cloudcraft
    ports:
    - protocol: TCP
        port: {{ .Values.service.port }}
        targetPort: 5000
    type: {{ .Values.service.type }}