apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cloudcraft
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-cloudcraft
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 5000 }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-cloudcraft