apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcraft
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manthan-parmar-1998/cloudcraft.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml
        - values-staging.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true