name: CloudCraft CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cloudcraft:latest
      
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker
          kubernetes-version: v1.28.0
          minikube-version: latest
          memory: 4096
          cpus: 2
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      
      - name: Deploy all environments
        run: |
          # Deploy to each environment
          for env in dev staging prod; do
            echo "Deploying to $env environment..."
            
            helm upgrade --install cloudcraft-$env ./helm \
              --values ./helm/values-$env.yaml \
              --set image.repository=${{ secrets.DOCKER_USERNAME }}/cloudcraft \
              --set image.tag=latest \
              --set image.pullPolicy=Always \
              --namespace $env --create-namespace \
              --wait --timeout=5m
            
            # Verify deployment
            kubectl wait --for=condition=available --timeout=300s deployment -l app=cloudcraft -n $env
            kubectl get all -n $env
          done
      
      - name: Show all deployments
        run: |
          echo "=== All Deployments ==="
          kubectl get deployments -A | grep cloudcraft
          echo "=== All Pods ==="
          kubectl get pods -A | grep cloudcraft